{
	"Animated": true,
	"Duration": 2,
	"IsIconHidden": false,
	"Message": "Entity deleted",
	"NumberOfLines": 2,
	"OnSuccess": "/SoltiusInnovMdk/Actions/GoodsIssue/CloseModalPage_Complete.action",
	"_Type": "Action.Type.ToastMessage"
}