{
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/SoltiusInnovMdk/Actions/GoodsIssue/OdataAction/Message/UpdateEntityFailureMessage.action",
	"OnSuccess": "/SoltiusInnovMdk/Actions/GoodsIssue/OdataAction/Message/UpdateEntitySuccessMessage.action",
	"Properties": {
		"CHANGEBY": "#Control:CHANGEBY/#Value",
		"CHANGEDAT": "#Control:CHANGEDAT/#Value",
		"CREATEBY": "#Control:CREATEBY/#Value",
		"CREATEDAT": "#Control:CREATEDAT/#Value",
		"DELIVERYCONFIRMATIONSTATUSCODE": "#Control:DELIVERYCONFIRMATIONSTATUSCODE/#Value",
		"DELIVERYDATE": "#Control:DELIVERYDATE/#Value",
		"DELIVERYGOODSISSUESTATUSCODE": "#Control:DELIVERYGOODSISSUESTATUSCODE/#Value",
		"DELIVERYID": "#Control:DELIVERYID/#Value",
		"DELIVERYPICKINGSTATUSCODE": "#Control:DELIVERYPICKINGSTATUSCODE/#Value",
		"EDITABLESTATUSCODE": "#Control:EDITABLESTATUSCODE/#Value",
		"GOODSISSUEACTUALDATE": "#Control:GOODSISSUEACTUALDATE/#Value",
		"GOODSISSUEID": "#Control:GOODSISSUEID/#Value",
		"SHIPTOPARTYID": "#Control:SHIPTOPARTYID/#Value",
		"SHIPTOPARTYNAME": "#Control:SHIPTOPARTYNAME/#Value"
	},
	"Target": {
		"EntitySet": "DeliveryHeader",
		"ReadLink": "{@odata.readLink}",
		"Service": "/SoltiusInnovMdk/Services/GoodsIssueHDBAllEntity.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}