{
	"Animated": true,
	"Duration": 2,
	"IsIconHidden": true,
	"Message": "Application data service initialized",
	"NumberOfLines": 2,
	"OnSuccess": "/SoltiusInnovMdk/Actions/GoodsIssue/Navigation/NavToGoodsIssue_Search.action",
	"_Type": "Action.Type.ToastMessage"
}