{
	"ActivityIndicatorText": "Activity Indicator Item",
	"OnSuccess": "/SoltiusInnovMdk/Actions/PutAway/OdataAction/Messages/MessageAction_Edit_Item_Success.action",
	"Properties": {
		"Bin": "#Control:FCAssignBin/#SelectedValue",
		"DeliveryNote": "#Control:FCDeliveryNote/#Value",
		"HeaderText": "#Control:FCHeaderText/#Value",
		"ItemText": "#Control:FCItemText/#Value",
		"MaterialDocument": "#Control:FCMaterialDocument/#Value",
		"Palette": "#Control:FCAssignPalette/#SelectedValue",
		"PartDescription": "#Control:FCPartDescription/#Value",
		"PartNumber": "#Control:FCPartNumber/#Value",
		"Plant": "#Control:FCPlant/#Value",
		"PurchaseOrder": "#Control:FCPurchaseOrder/#Value",
		"Quantity": "#Control:FCQuantityUOM/#Value",
		"Sloc": "#Control:FCLineItem/#Value",
		"VendorDescription": "#Control:FCVendorDescription/#Value"
	},
	"ShowActivityIndicator": true,
	"Target": {
		"EntitySet": "PutawayProcess",
		"Service": "/SoltiusInnovMdk/Services/PutAwayHDBAllEntity.service"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}